name: Build and deploy Node.js app to Azure Web App - novelistanbackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: npm install and build backend
        run: |
          cd backend
          npm ci
          npm run build --if-present
          
      - name: Verify build output and prepare for deployment
        run: |
          echo "Directory contents of backend folder:"
          ls -la backend
          
      - name: Zip artifact for deployment
        run: |
          cd backend
          # Exclude unnecessary files from the zip to reduce size
          zip -r ../release.zip . -x "node_modules/*" ".git/*" ".github/*" ".env*" "*.zip"
          cd ..
          echo "Zip file created with size:"
          ls -la release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: |
          unzip -o release.zip -d .
          echo "Unzipped contents:"
          ls -la
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App with detailed logging'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'novelistanbackend'
          slot-name: 'Production'
          package: .
          respect-pom-xml: false
          verbose: true
