# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - novelistanAI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Backend - npm install, build, and test
        run: |
          cd backend
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Frontend - npm install, build, and test
        run: |
          cd novelistan
          npm install
          npm run build --if-present

      - name: Build frontend assets
        run: |
          cd novelistan
          # Verify build output exists
          if (Test-Path -Path "dist") {
            echo "Frontend build output found in dist directory"
          } else {
            echo "ERROR: Frontend dist directory not found! Build may have failed."
            exit 1
          }
          
          # Ensure target directory exists and is empty
          echo "Creating clean frontend directory in backend/public/frontend"
          if (Test-Path -Path "../backend/public/frontend") {
            Remove-Item -Path "../backend/public/frontend" -Recurse -Force
          }
          New-Item -ItemType Directory -Path "../backend/public/frontend" -Force
          
          # Copy frontend build files to backend/public/frontend
          echo "Copying frontend build to backend/public/frontend"
          Copy-Item -Path "dist/*" -Destination "../backend/public/frontend/" -Recurse -Force
          
          # Verify copy was successful
          if (Test-Path -Path "../backend/public/frontend/index.html") {
            echo "Frontend successfully copied to backend/public/frontend"
          } else {
            echo "ERROR: Frontend copy failed! index.html not found in destination."
            exit 1
          }

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend
          # Only include backend files for Azure deployment

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'novelistanAI'
          slot-name: 'Production'
          package: .